version: '3.9'

services:  

  postgres-db:
    container_name: postgres
    image: postgres
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - milliy
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  migrate:
    image: migrate/migrate
    networks:
      - milliy
    volumes:
      - ./migrations:/migrations
    depends_on:
      - postgres-db
    command: ["-path", "/migrations", "-database" ,"postgres://${DB_USER}:${DB_PASSWORD}@postgres:${DB_PORT}/${DB_NAME}?sslmode=disable","up"]

  api-service:
    container_name: api-gateway
    build: .
    depends_on:
      postgres-db:
        condition: service_healthy
    ports:
      - "4444:4444"
    networks:
     - milliy
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:4444/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  minio:
    image: docker.io/bitnami/minio:2024
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - minio_data:/bitnami/minio/data
    environment:
      - MINIO_ROOT_USER=${MINIO_ACCESS_KEY_ID}
      - MINIO_ROOT_PASSWORD=${MINIO_SECRET_ACCESS_KEY}
      - MINIO_SERVER_URL=https://media.harbiytarbiya.uz # Public URL
      - MINIO_BROWSER_REDIRECT_URL=https://media.harbiytarbiya.uz
      - MINIO_DEFAULT_BUCKETS=photos,videos,musics
    networks:
      - milliy
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:9000/minio/health/live || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 5

networks:
  milliy:
    external: true


volumes:
  minio_data:
    driver: local
  db:
    driver: local
   