CREATE TYPE roles AS ENUM ('admin');

CREATE TABLE IF NOT EXISTS users (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    login VARCHAR(100) UNIQUE NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    role roles NOT NULL DEFAULT 'admin',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    deleted_at Bigint DEFAULT 0
);



CREATE TABLE IF NOT EXISTS twit(
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL REFERENCES users(id),
    title TEXT NOT NULL,
    texts TEXT NOT NULL,
    readers_count INTEGER,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    deleted_at Bigint DEFAULT 0
);


CREATE TABLE IF NOT EXISTS videos(
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    twit_id UUID REFERENCES twit(id),
    video VARCHAR(200) UNIQUE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    deleted_at Bigint DEFAULT 0
);

CREATE TABLE IF NOT EXISTS photos(
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    twit_id UUID REFERENCES twit(id),
    photo VARCHAR(200) UNIQUE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    deleted_at Bigint DEFAULT 0
);


CREATE TABLE IF NOT EXISTS musics(
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    twit_id UUID REFERENCES twit(id),
    mp3 VARCHAR(200) UNIQUE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    deleted_at Bigint DEFAULT 0
)



CREATE TABLE IF NOT EXISTS locations(
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    twit_id UUID REFERENCES twit(id),
    lat VARCHAR(50) NOT NULL,
    lon VARCHAR(50) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    deleted_at Bigint DEFAULT 0
)

CREATE TABLE IF NOT EXISTS urls(
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    twit_id UUID REFERENCES twit(id),
    url VARCHAR(200) UNIQUE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    deleted_at Bigint DEFAULT 0
)