CREATE TABLE IF NOT EXISTS saved (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    twit_id UUID REFERENCES twit(id),
    start_time TIMESTAMP WITH TIME ZONE,
    end_time TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    deleted_at Bigint DEFAULT 0
);